### ISSUE TITLE
Peer-to-peer Code Rewiew

### ISSUE THREAD

**Issue by mgmediaweb** [Draxeytina/Live-Album-Launch#2]
Your code looks pretty good, congratulations on that, however, we can suggest the following points:

- Kindly ensure that your mobile version does not have any horizontal scrolling.
- Kindly add the top nav menu in the header.
- Check your design with the provided one.
- Kindly you should use the original font "Lato".
- Kindly the black bar on top should be more narrow.
- Not use double **br** is prefer to use another **p** tag.
- Kindly, you shouldn't use separate lines for titles, include them as a background images in titles.
- In the mobile version disappear the main logo.
- Delete about.js (it's blank).
- Kindly you should make a folder to organize the CSS and JS files.

**Comment by Draxeytina** [comment]
All issues noted thank you.
